import { useState, useEffect, useRef, useLayoutEffect } from "react";

/* ════════════════════════════════════════
   MATH HELPERS
════════════════════════════════════════ */
const clamp = (v, lo = 0, hi = 1) => Math.min(Math.max(v, lo), hi);
const lerp = (a, b, t) => a + (b - a) * clamp(t);
const prog = (p, s, e) => clamp((p - s) / (e - s));
const easeOut = (t) => 1 - Math.pow(1 - t, 3);
const easeOut4 = (t) => 1 - Math.pow(1 - t, 4);
const easeInOut = (t) => t < 0.5 ? 4 * t * t * t : 1 - Math.pow(-2 * t + 2, 3) / 2;

/* ════════════════════════════════════════
   IMAGES
════════════════════════════════════════ */
const mainimage = "https://images.klipfolio.com/website/public/bf9c6fbb-06bf-4f1d-88a7-d02b70902bd1/data-dashboard.png";
const FR = mainimage;
const GRC = "https://www.workiva.com/sites/workiva/files/styles/16_9_rectangle_2384x1341/public/images/platform-graphics/wk-home-hero-grc.png.webp";
const ESG = "https://www.workiva.com/sites/workiva/files/styles/16_9_rectangle_1088x612/public/images/platform-graphics/wk-home-hero-sustainability.png.webp";

/* ════════════════════════════════════════
   SUBCOMPONENTS
════════════════════════════════════════ */
const MacDots = () => (
  <div className="flex gap-1">
    {["#ff5f57", "#febc2e", "#28c840"].map(c => (
      <div key={c} className="w-2.5 h-2.5 rounded-full" style={{ background: c }} />
    ))}
  </div>
);

const ChromeBar = ({ url }) => (
  <div className="flex items-center gap-2.5 bg-[#1e2433] p-2.5">
    <MacDots />
    <div className="flex-1 bg-[#252d40] rounded px-3 py-1 max-w-[300px]">
      <span className="text-[10px] text-white/30 font-sans">{url}</span>
    </div>
  </div>
);

const AIPanel = () => (
  <div className="w-[292px] bg-white rounded-xl border border-gray-200 shadow-2xl overflow-hidden font-sans">
    <div className="flex items-center justify-between p-3 bg-gray-50 border-b border-gray-200">
      <div className="flex items-center gap-2">
        <div className="w-5 h-5 rounded bg-gradient-to-br from-blue-500 to-green-500 flex items-center justify-center">
          <span className="text-white text-[10px] font-bold">W</span>
        </div>
        <span className="text-[13px] font-bold text-gray-900">Workiva AI</span>
      </div>
      <div className="flex gap-2 items-center">
        <span className="text-blue-600 font-semibold text-[12px] cursor-pointer">Clear chat</span>
        <span className="text-gray-400 text-[15px]">✕</span>
      </div>
    </div>
    <div className="p-3">
      <div className="text-[11px] text-gray-500 mb-2">
        Intelligence: <span className="text-blue-600 font-semibold">General ▾</span>
      </div>
      <div className="bg-gray-100 rounded-lg p-3 mb-2 flex gap-2 items-start">
        <p className="flex-1 text-[12px] text-gray-700 leading-6 m-0">
          Referencing the financial data in this table, draft a narrative highlighting significant year-over-year changes.
        </p>
        <span className="text-gray-400 text-[18px] flex-shrink-0">▷</span>
      </div>
      <p className="text-[10px] text-gray-400 text-center m-0">
        Content generated by AI. Review for accuracy. ⓘ
      </p>
    </div>
  </div>
);

const ControlTable = () => (
  <div className="w-[430px] bg-white rounded-xl border-2.5 border-green-500 shadow-2xl overflow-hidden font-sans">
    <div className="bg-green-50 p-3 border-b border-green-100">
      <span className="text-[11.5px] font-bold text-green-800">
        ↑ Control ID &nbsp;&nbsp; Description &nbsp;&nbsp; Process &nbsp;&nbsp; Sub proc…
      </span>
    </div>
    {[
      ["EXP.005", "Check Settlement…", "Procure to Pay…", "Expendit…"],
      ["FR.005", "On a quarterly bas…", "General Ledger…", "Financi…"],
      ["FA.003", "The Sr. Director of…", "FP&A…", "Fixed As…"],
      ["SUS.CSR.004", "Physical climate ri…", "Sustainability…", "Corporat…"],
    ].map(([id, d, pr, s], i) => (
      <div key={i} className="grid grid-cols-[108px_1fr_108px_76px] items-center p-2.5 border-b border-green-50">
        <span className="text-blue-600 font-semibold text-[11.5px]">{id}</span>
        <span className="text-gray-700 text-[11px]">{d}</span>
        <span className="text-gray-700 text-[11px]">{pr}</span>
        <span className="text-gray-700 text-[11px]">{s}</span>
      </div>
    ))}
  </div>
);

/* ════════════════════════════════════════
   MAIN APP
════════════════════════════════════════ */
export default function DashboardScrollUI() {
  const containerRef = useRef(null);
  const rawRef = useRef(0);
  const smoothRef = useRef(0);
  const rafRef = useRef(null);
  const [p, setP] = useState(0);

  /* ── scroll reader ── */
  useEffect(() => {
    const read = () => {
      const el = containerRef.current; if (!el) return;
      const rect = el.getBoundingClientRect();
      const total = el.offsetHeight - window.innerHeight;
      rawRef.current = clamp(-rect.top / total);
      setP(rawRef.current);
    };
    window.addEventListener("scroll", read, { passive: true });
    read();
    return () => window.removeEventListener("scroll", read);
  }, []);

  /* ── 60 fps smoothing ── */
  useLayoutEffect(() => {
    const tick = () => {
      const d = rawRef.current - smoothRef.current;
      smoothRef.current += d * 0.07;
      setP(Math.abs(d) < 0.0002 ? rawRef.current : smoothRef.current);
      rafRef.current = requestAnimationFrame(tick);
    };
    rafRef.current = requestAnimationFrame(tick);
    return () => cancelAnimationFrame(rafRef.current);
  }, []);

  /* ── PRODUCT MODES ── */
  const productModes = [
    {
      key: "audit",
      label: "Audit Management",
      headline: "Audit",
      subhead: "Findings, controls, and reporting in one flow.",
      button: "Explore Audit",
      image: FR,
      bg: "#0f6bf2",
    },
    {
      key: "grc",
      label: "GRC",
      headline: "GRC",
      subhead: "Governance, risk, and compliance across the enterprise.",
      button: "Explore GRC",
      image: GRC,
      bg: "#181c24",
    },
    {
      key: "esg",
      label: "ESG Platform",
      headline: "ESG",
      subhead: "Sustainability, corporate responsibility, and reporting.",
      button: "Explore ESG",
      image: ESG,
      bg: "#18ee92",
    },
  ];

  const modeIndex = Math.min(2, Math.max(0, Math.floor(prog(p, 0.33, 1) * 3)));
  const currentMode = productModes[modeIndex];

  /* ── Background color transition ── */
  const getBg = () => {
    if (p < 0.33) return "#f9fafb"; // main dashboard
    if (p < 0.66) return productModes[0].bg; // first product
    if (p < 0.9) return productModes[1].bg; // second product
    return productModes[2].bg; // third product
  };

  const bg = getBg();

  return (
 <div ref={containerRef} className="relative font-sans" style={{ background: bg }}>
      <div style={{ height: "400vh", position: "relative" }}>
        {/* Sticky viewport */}
        <div className="sticky top-0 h-screen w-full flex flex-col md:flex-row overflow-hidden" style={{ background: bg, transition: "background 0.3s" }}>

          {/* LEFT TEXT PANEL */}
          <div className="md:w-1/2 p-10 md:p-20 flex flex-col justify-center text-white" style={{
            opacity: easeOut(prog(p, 0.1, 0.9)),
            transform: `translateX(${lerp(-50, 0, easeOut(prog(p, 0.1, 0.9)))}px)`,
            transition: "opacity 0.3s, transform 0.3s",
          }}>
            <p className="uppercase tracking-widest mb-4">{currentMode.label}</p>
            <h2 className="text-5xl md:text-6xl font-extrabold mb-4">{currentMode.headline}.<br />{currentMode.subhead}</h2>
            <button className="bg-blue-600 px-8 py-4 rounded-full font-bold shadow-lg">{currentMode.button}</button>
          </div>

          {/* RIGHT IMAGE PANEL */}
          <div className="md:w-1/2 p-10 md:p-20 flex justify-center items-center">
            <div className="relative w-full h-full">
              <img src={currentMode.image} alt={currentMode.headline} className="rounded-2xl shadow-2xl w-full max-w-lg" />
            </div>
          </div>

        </div>
      </div>
    </div>
  );
}